# Site settings
title: "LiangChao Xu"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "LiangChao Xu"
resume_title:                   "Biography   email:kevinxu11155@gmail.com"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kevinxu11155@gmail.com" 

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "kevinxu11155@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I'm a sophomore(second year) student from <a href='https://ise.nju.edu.cn'>School of Intelligent Software and Engineering</a>, <a href='https://www.nju.edu.cn'>NanJing University</a>, and I'm very fortunate to be advised by <a href='https://yoyo000.github.io/'>Prof. Yao</a> of 3D Vision Lab from <a href='https://is.nju.edu.cn/'>School of Intelligence Science and Technology</a>, NanJing University. My research interest includes 3D Vision, Computer Vision, and Machine learning.</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/KevinXu11155"
  #resume_twitter_url:           
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "kevinxu11155@gmail.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
